# https://www.yamllint.com/ for formatting.
name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.3.0'

      - name: Install dependencies
        run: npm install

      - name: Check for vulnerabilities
        run: |
          npm audit --audit-level=moderate || echo "Audit completed with warnings"

      - name: Attempt to fix vulnerabilities
        run: |
          npm audit fix || echo "Automatic fixes not applied"

      - name: Re-check vulnerabilities
        run: |
          npm audit --audit-level=moderate || echo "Remaining vulnerabilities need manual intervention"

      - name: Load environment variables
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
        run: npx dotenv-vault pull development
        continue-on-error: true
